### ISSUE TITLE
Some refseq ID cannot be recognized

### ISSUE THREAD

**Issue by YanSiyuanVicky** [stjude/ROSE#16]
Dear ROSE developers,
Thank you very much for developing ‘ROSE’! It's of great help to our enhancer research. However, we found in our study nearly half of the refseq IDs could not be recognized by ROSE in our study .

The command line is: 
`ROSE_geneMapper.py -g hg38 -i test.txt  --list symbol2refseq_G1.txt  -o /home/suiyi/YSY/ROSE-1.3.1`
It returned that: 
`Traceback (most recent call last):`
  `File "/home/suiyi/YSY/ROSE-1.3.1//bin/ROSE_geneMapper.py", line 291, in <module> main()`
  `File "/home/suiyi/YSY/ROSE-1.3.1//bin/ROSE_geneMapper.py", line 277, in main enhancerToGeneTable,geneToEnhancerTable =mapEnhancerToGene(annotFile,enhancerFile,uniqueGenes=True,byRefseq=options.refseq, transcribedFile=transcribedFile)`
  `File "/home/suiyi/YSY/ROSE-1.3.1//bin/ROSE_geneMapper.py", line 55, in mapEnhancerToGene tssLoci.append(ROSE_
[synbol2refseq_G1.txt](https://github.com/stjude/ROSE/files/8549768/synbol2refseq_G1.txt)
utils.makeTSSLocus(geneID,startDict,0,0))`
  `File "/home/suiyi/YSY/ROSE-1.3.1/lib/ROSE_utils.py", line 527, in makeTSSLocus start = startDict[gene]['start'][0]`
  `KeyError: 'NM_001002847'`

Once the transcript ID 'NM_001002847' was deleted, the run will go on until reporting the next refseq ID it could not recognize. The genelist was transferred by biomaRt in R. The unrecognized ID almost accounted for half of the genelist.  
Any help is appreciated. Thank you very much！

Best regards,
Yan Siyuan
2022/04/24

The python3 version ROSE was downloaded from [https://github.com/stjude/ROSE](https://github.com/stjude/ROSE) .
samtools 1.15.1, bedtools v2.30.0, R version 4.1.3, Python 3.9.12 have been installed.

The genelist file:
[symbol2refseq_G1.txt](https://github.com/stjude/ROSE/files/8549775/symbol2refseq_G1.txt)
The enhancer file for input: 
[test.txt](https://github.com/stjude/ROSE/files/8549802/test.txt)

**Comment by madetunj** [comment]
The error is because the annotation file provided in our program ([hg38](https://raw.githubusercontent.com/stjude/ROSE/master/annotation/hg38_refseq.ucsc)), does not include the some of the genes listed in your genelist. To correct for this, provide your annotation file that can be generated or obtained from the UCSC and use `--custom`.

**Comment by YanSiyuanVicky** [comment]
Thank you for your quick reply!  It worked！Really appreciate your help!

**Comment by sky5198** [comment]
Thank you for creating this tool! I am excited to see the output of my data but I am stuck on the last step. 

I switched references to an annotation file from NCBI for HG38 obtained from USCS (https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=2561587304_pSx1hjWks91kuevZp7DN91HGEccQ&clade=mammal&org=Human&db=hg38&hgta_group=genes&hgta_track=refSeqComposite&hgta_table=0&hgta_regionType=genome&position=chr7%3A155%2C799%2C529-155%2C812%2C871&hgta_outputType=primaryTable&hgta_outFileName=hg38_HGNC_refseq.ucsc) which got me a lot further but I still receive a KeyError. When I go back to my annotation file, the genes are included in the annotation file so I am not sure why it is stopping.

Do you have any further suggestions? I am at a loss since I see the genes in the annotation file and it should be included. 



KeyError: 'LOC105370327'
